worker_processes auto;
events { worker_connections 1024; }
http {
  upstream app { server app:3000; }
  server {
    listen 80;
    server_name _;
    client_max_body_size 100m;
    location / {
      proxy_pass http://app;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection 'upgrade';
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_cache_bypass $http_upgrade;
    }
  }
}
